import { Mission } from "../types";
import { ALL_MISSIONS } from "../sampleMissions";
import { MissionDetailData } from "./detailTypes";

export function getMissionDetailData(id: string): MissionDetailData {
  const mission = ALL_MISSIONS.find((m) => m.id === id) || {
    id: id || "stop-api-crashing-traffic-spikes",
    title: "Stop an API from Crashing Under Traffic Spikes",
    description: "Implement a Redis-backed Sliding Window Log rate limiter to gracefully protect downstream services during 100k req/min traffic surges.",
    difficulty: "Medium" as const,
    category: "Backend" as const,
    timeEstimate: "2 hrs",
    xpReward: 500,
    techStack: ["Redis", "Node.js", "TypeScript"],
    skills: ["Rate Limiting", "Concurrency", "API Design", "Redis Lua"],
    status: "In Progress" as const,
    progress: 37,
    currentStep: 3,
    totalSteps: 8,
    activeFile: "limiter.ts",
    benchmarkTarget: "< 5ms latency overhead at 10,000 req/sec",
  };

  return {
    mission,
    problemStatement: {
      what: `During unexpected traffic surges (e.g. flash sales, viral social events, or DDoS spikes), unthrottled API endpoints consume all available database connections, leading to thread pool exhaustion, cascading HTTP 504 Gateway Timeouts, and total service outages.`,
      why: `Unprotected API endpoints allow bad actors or runaway client retries to monopolize system resources. Without strict rate limiting at the edge, a single spike in requests can bring down your primary database and degrade customer experience globally.`,
      who: `E-commerce platforms, payment APIs, microservices, public developer platforms, and authentication gateways handling high concurrent user velocity.`,
      businessImpact: `Service outages cause thousands of dollars per minute in lost transactions, breach customer SLAs, degrade search engine rankings, and destroy user trust during critical product events.`,
      engineeringImpact: `Database connection pool exhaustion, CPU spike to 100%, cascading worker thread crashes, unbounded memory leaks, and delayed background job executions.`,
      howCompaniesSolve: `Production systems implement Redis-backed Sliding Window Log or Token Bucket algorithms wrapped in atomic Lua scripts. Requests are intercepted at the API Gateway layer in sub-5ms before hitting underlying databases.`,
    },
    realWorldCompanies: [
      {
        name: "Stripe",
        logo: "stripe",
        description: "Enforces multi-tier rate limiting across millions of financial transactions using Redis cluster token buckets to guarantee zero payment downtime.",
        scaleMetric: "500M+ daily requests protected",
      },
      {
        name: "GitHub",
        logo: "github",
        description: "Uses sliding window log rate limiters for GraphQL and REST API endpoints to preserve system stability during viral code releases.",
        scaleMetric: "5,000 req/hour per authenticated user",
      },
      {
        name: "Cloudflare",
        logo: "cloudflare",
        description: "Processes edge rate limiting across 300+ global data centers to stop layer-7 DDoS traffic in sub-millisecond execution loops.",
        scaleMetric: "67M requests per second throttled",
      },
      {
        name: "Discord",
        logo: "discord",
        description: "Implements distributed leaky bucket limiters across WebSocket gateway connections to handle real-time chat bursts.",
        scaleMetric: "12M+ concurrent connection handles",
      },
    ],
    learningObjectives: [
      "Master Redis Sliding Window Log and Token Bucket rate limiting algorithms",
      "Write atomic Redis Lua scripts to eliminate concurrent race condition bugs",
      "Diagnose event loop thread pool starvation under high concurrent load",
      "Implement graceful HTTP 429 Too Many Requests response headers (Retry-After, X-RateLimit-Remaining)",
      "Set up automated sub-5ms performance benchmark test suites using k6 / Autocannon",
      "Publish a verified, recruiter-ready Proof of Work repository showcasing system resilience",
    ],
    roadmapSteps: [
      {
        stepNumber: 1,
        title: "Analyze Failing Production Logs & Traffic Metrics",
        description: "Examine HTTP 504 logs, CPU thread starvation spikes, and identify why naive counter approaches fail under concurrent requests.",
        timeEstimate: "15 min",
        difficulty: "Easy",
        status: "Completed",
        keyFile: "logs/traffic_dump.log",
      },
      {
        stepNumber: 2,
        title: "Set Up Redis Connection & Development Sandbox",
        description: "Configure ioredis connection pooler with maxRetriesPerRequest and automated reconnection handlers.",
        timeEstimate: "20 min",
        difficulty: "Easy",
        status: "Completed",
        keyFile: "redis.ts",
      },
      {
        stepNumber: 3,
        title: "Implement Naive Fixed Window Rate Limiter",
        description: "Build a basic key-based INCR counter in Redis and run concurrent test scripts to reveal window boundary exploit bugs.",
        timeEstimate: "25 min",
        difficulty: "Medium",
        status: "Current",
        keyFile: "limiter.ts",
      },
      {
        stepNumber: 4,
        title: "Upgrade to Sliding Window Log Algorithm",
        description: "Use Redis Sorted Sets (ZSET) storing timestamps as scores to track exact request windows dynamically.",
        timeEstimate: "35 min",
        difficulty: "Hard",
        status: "Locked",
        keyFile: "sliding_window.ts",
      },
      {
        stepNumber: 5,
        title: "Encapsulate Logic in Atomic Redis Lua Script",
        description: "Prevent non-atomic multi-step race conditions by executing ZREMRANGEBYSCORE, ZADD, and ZCARD atomically on Redis single thread.",
        timeEstimate: "30 min",
        difficulty: "Hard",
        status: "Locked",
        keyFile: "ratelimit.lua",
      },
      {
        stepNumber: 6,
        title: "Attach HTTP Express / Fastify Middleware",
        description: "Inject rate limit middleware setting X-RateLimit-Limit, X-RateLimit-Remaining, and Retry-After headers.",
        timeEstimate: "20 min",
        difficulty: "Medium",
        status: "Locked",
        keyFile: "middleware.ts",
      },
      {
        stepNumber: 7,
        title: "Run Load Benchmark & Resilience Tests",
        description: "Execute 10,000 concurrent requests/sec tests to verify P99 latency stays under 5ms without memory leaks.",
        timeEstimate: "25 min",
        difficulty: "Hard",
        status: "Locked",
        keyFile: "tests/benchmark.ts",
      },
      {
        stepNumber: 8,
        title: "Socratic AI Code Review & Publish Proof of Work",
        description: "Pass AI Senior Coach review on edge cases (Redis cluster failover, local memory fallback) and publish Proof of Work.",
        timeEstimate: "15 min",
        difficulty: "Medium",
        status: "Locked",
        keyFile: "proof_of_work.md",
      },
    ],
    technologyDetails: [
      {
        name: "Redis",
        role: "In-Memory Datastore & Cache",
        whyUsed: "Provides sub-millisecond atomic operations (`ZSET`, `INCR`, Lua execution) for shared distributed state across microservices.",
        category: "Datastore",
      },
      {
        name: "Node.js",
        role: "Async Runtime Engine",
        whyUsed: "Non-blocking event-driven IO model allows handling thousands of concurrent HTTP socket connections efficiently.",
        category: "Runtime",
      },
      {
        name: "TypeScript",
        role: "Type Safety & Contracts",
        whyUsed: "Ensures strict parameter validation, type-safe middleware request extensions, and zero runtime type errors.",
        category: "Language",
      },
      {
        name: "Docker",
        role: "Containerized Environment",
        whyUsed: "Spins up reproducible Redis 7 Alpine containers matching exact production microservice setups.",
        category: "DevOps",
      },
    ],
    deliverablesList: [
      "Working Rate Limiting Middleware with Redis Lua Atomicity",
      "Passing Automated Integration & Race Condition Test Suites",
      "Sub-5ms Latency Benchmark Verification Log",
      "GitHub Production Repository with Architecture Documentation",
      "Verified Proof of Work Certificate with AI Understanding Score",
    ],
    acceptanceCriteria: [
      "100% automated test suite passing (0 failed assertions)",
      "Sub-5ms P99 execution latency overhead at 10,000 req/sec",
      "0 race condition double-refill or limit bypass bugs during 500 concurrent workers",
      "Proper HTTP 429 status code and X-RateLimit-* response headers on throttled requests",
      "AI Senior Coach Understanding Score >= 85%",
    ],
    aiCoachGuidelines: [
      "Reviews your Redis Lua script for non-atomic script breakages",
      "Challenges your memory overhead assumptions on high-cardinality IP keys",
      "Asks probing questions when fallback memory mechanisms are omitted",
      "Provides progressive Hints without ever handing over raw solution copy-paste",
    ],
    proofOfWorkSnippet: {
      title: "Resilient Redis Sliding Window Rate Limiter Engine",
      author: "Sai (Systems Builder)",
      score: 94,
      githubRepo: "https://github.com/makemistakes/redis-rate-limiter",
      reflectionSummary: "Replaced fixed window counter with atomic Redis ZSET Lua script, eliminating 100% of boundary traffic spikes and reducing P99 latency to 3.2ms under 10k req/sec.",
      keyMetricAchieved: "P99 Latency: 3.2ms | Zero Race Condition Failures",
    },
    stats: {
      completionRate: "91.4%",
      avgTimeSpent: "2h 15m",
      difficultyRating: "3.8 / 5.0",
      studentRating: "4.9 / 5.0 (340+ reviews)",
      commonMistake: "Forgetting atomic ZREMRANGEBYSCORE execution leading to race conditions between ZCARD check and ZADD write.",
      topSkill: "Atomic Distributed Concurrency (Redis Lua)",
    },
  };
}
